image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - bungcip.better-toml
    - matklad.rust-analyzer
    - swellaby.vscode-rust-test-adapter
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
