image:
  file: .gitpod.Dockerfile

tasks:
  - name: Deploy dev environment and build all targets
    before: ./scripts/dev_env.sh
    init: cargo build --all-targets

vscode:
  extensions:
    - tamasfe.even-better-toml
    - matklad.rust-analyzer
