unstable_features = true

max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

match_block_trailing_comma = true
use_field_init_shorthand = true
