version: '3.9'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENVIRONMENT=production
      - CONDUIT__APP__JWT_SECRET=2DgSjrVwFXLYFz
      - CONDUIT__DATABASE__HOST=db
      - CONDUIT__DATABASE__USERNAME=postgres
      - CONDUIT__DATABASE__PASSWORD=password
      - CONDUIT__DATABASE__DATABASE_NAME=conduit
      - CONDUIT__DATABASE__SSL=false
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=conduit
  # For running sqlx migrations
  migrations:
    build:
      context: ..
      dockerfile: docker/migrations.Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=conduit
    depends_on:
      - db
